events {}

http {

    upstream tomcat_servers {

        server tomcat1:8080;
        server tomcat2:8080;

    }

    server {

        listen 80;

        location / {

            proxy_pass http://tomcat_servers;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }
    }
}
